/**
 * Parts catalog for the AI Construct Designer — E. coli, Mammalian, Yeast.
 *
 * All sequences are real and sourced from our annotation database
 * (public/data/features.json), which was built from SnapGene public plasmid
 * library + iGEM Registry features clustered at 80% identity.
 *
 * To update sequences after features.json grows (e.g., Addgene expansion):
 *   python3 scripts/update-parts-catalog.py
 *   # then embed the sequences from data/parts-sequences.json here
 *
 * Parts not yet in the database (CmR, pSC101 ori) are omitted until
 * the sequences can be verified. AmpR + KanR cover >95% of E. coli use cases.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type PartType = "promoter" | "rbs" | "terminator" | "ori" | "marker" | "cds";
export type Organism = "ecoli" | "mammalian" | "yeast" | "universal";

export interface Part {
  id: string;
  name: string;
  type: PartType;
  organisms: Organism[];
  /** Human-readable description sent to Claude as selection context. */
  description: string;
  seq: string;
  /** Typed now for schema stability; populated as metadata expands. */
  strength?: "strong" | "medium" | "weak";
  /** Inducer molecule, if applicable. */
  inducibleBy?: string;
  /** Plasmid copies per cell (ori only). */
  copyNumber?: number;
  /** Restriction enzymes that cut within this part — avoid for cloning. */
  internalRestrictionSites?: string[];
  /** Source for sequence traceability. */
  source?: string;
}

// ── Catalog ───────────────────────────────────────────────────────────────────

export const PARTS_CATALOG: Part[] = [
  // ── Promoters ──────────────────────────────────────────────────────────────

  {
    id: "t7_promoter",
    name: "T7 promoter",
    type: "promoter",
    organisms: ["ecoli"],
    description:
      "Very strong promoter recognized exclusively by T7 RNA polymerase. Requires BL21(DE3) or similar strains harboring chromosomal T7 RNAP. Highest expression levels of any E. coli promoter. IPTG-inducible via the T7 RNAP gene control. Use for maximum protein yield when T7-compatible cells are available.",
    seq: "TAATACGACTCACTATAGGG",
    strength: "strong",
    inducibleBy: "IPTG (via T7 RNAP)",
    source: "T7 phage genome, phi10 promoter consensus (20 bp core)",
  },
  {
    id: "tac_promoter",
    name: "tac promoter",
    type: "promoter",
    organisms: ["ecoli"],
    description:
      "Hybrid trp-lac promoter. Strong, directly IPTG-inducible in any standard E. coli strain — no T7 RNAP required. Produces high levels of recombinant protein with good induction control. Used in pGEX, pMAL, and many expression vectors. Requires lacI repressor for tight control (present in DH5α, BL21, most lab strains).",
    seq: "TTGACAATTAATCATCGGCTCGTATAATGTGTGGAATTGTGAGCGGATAACAATTTCACACAGG",
    strength: "strong",
    inducibleBy: "IPTG",
    source: "de Boer et al. 1983, Proc Natl Acad Sci (64 bp, includes -35, -10, and lac operator)",
  },
  {
    id: "araBAD_promoter",
    name: "araBAD promoter",
    type: "promoter",
    organisms: ["ecoli"],
    description:
      "Arabinose-inducible promoter with tight repression in glucose. Excellent for toxic proteins due to very low leakage. Induced by L-arabinose; repressed by glucose. Lower expression than T7 or tac but tighter control. Good for difficult-to-express or toxic proteins.",
    seq: "AAGAAACCAATTGTCCATATTGCATCAGACATTGCCGTCACTGCGTCTTTTACTGGCTCTTCTCGCTAACCAAACCGGTAACCCCGCTTATTAAAAGCATTCTGTAACAAAGCGGGACCAAAGCCATGACAAAAACGCGTAACAAAAGTGTCTATAATCACGGCAGAAAAGTCCACATTGATTATTTGCACGGCGTCACACTTTGCTATGCCATAGCATTTTTATCCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCAT",
    strength: "medium",
    inducibleBy: "arabinose",
    source: "features.json: araBAD promoter (285 bp) from pBAD vector series",
  },
  {
    id: "j23119_promoter",
    name: "J23119 (constitutive, strong)",
    type: "promoter",
    organisms: ["ecoli"],
    description:
      "Strong constitutive promoter from the iGEM Anderson Promoter Library. No induction required — produces protein continuously. Good for selection markers, reporter genes, or when constitutive expression is desired.",
    seq: "TTGACAGCTAGCTCAGTCCTAGGTATAATGCTAGC",
    strength: "strong",
    source: "iGEM Registry BBa_J23119, Anderson Promoter Library (35 bp)",
  },
  {
    id: "j23101_promoter",
    name: "J23101 (constitutive, medium)",
    type: "promoter",
    organisms: ["ecoli"],
    description:
      "Medium-strength constitutive promoter from the iGEM Anderson Promoter Library. Useful when strong constitutive expression causes growth burden.",
    seq: "TTTACAGCTAGCTCAGTCCTAGGTATTATGCTAGC",
    strength: "medium",
    source: "iGEM Registry BBa_J23101, Anderson Promoter Library (35 bp)",
  },

  // ── Ribosome Binding Sites ─────────────────────────────────────────────────

  {
    id: "b0034_rbs",
    name: "RBS B0034 (strong)",
    type: "rbs",
    organisms: ["ecoli"],
    description:
      "Strong ribosome binding site from the iGEM Registry. Contains a strong Shine-Dalgarno sequence with optimal spacing. Use with strong promoters for maximum translation.",
    seq: "AAAGAGGAGAAATACTA",
    strength: "strong",
    source: "iGEM Registry BBa_B0034 (17 bp)",
  },
  {
    id: "b0032_rbs",
    name: "RBS B0032 (medium)",
    type: "rbs",
    organisms: ["ecoli"],
    description:
      "Medium-strength RBS. Lower translation rate reduces metabolic burden and can improve folding of difficult proteins. Use when strong RBS + strong promoter causes insolubility.",
    seq: "AAAGAGGAG",
    strength: "medium",
    source: "iGEM Registry BBa_B0032 (9 bp)",
  },

  // ── Terminators ────────────────────────────────────────────────────────────

  {
    id: "t7_terminator",
    name: "T7 terminator",
    type: "terminator",
    organisms: ["ecoli"],
    description:
      "Strong transcriptional terminator from T7 phage. Works with both T7 and bacterial RNA polymerases. Efficient stem-loop prevents read-through. Pair with T7 promoter or any strong E. coli promoter.",
    seq: "CTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTG",
    source: "features.json: T7 terminator (48 bp)",
  },
  {
    id: "rrnB_T1T2",
    name: "rrnB T1T2 terminator",
    type: "terminator",
    organisms: ["ecoli"],
    description:
      "Double terminator from the E. coli rrnB ribosomal RNA operon. Two sequential terminators (T1 then T2) provide very high termination efficiency. Reduces read-through into downstream sequences. Commonly used in pET and many expression vectors.",
    seq: "ATTTGTCCTACTCAGGAGAGCGTTCACCGACAAACAACAGATAAAACGAAAGGCCCAGTCTTCCGACTGAGCCTTTCGTTTTATTTGAGAAGGCCATCCTGACGGATGGCCTTTT",
    source: "features.json: rrnB T1 (87 bp) + rrnB T2 (28 bp) = 115 bp",
  },

  // ── Origins of Replication ─────────────────────────────────────────────────

  {
    id: "colE1_ori",
    name: "ColE1/pMB1 origin",
    type: "ori",
    organisms: ["ecoli"],
    description:
      "High-copy origin of replication (~500 copies/cell). Used in pUC, pBluescript, pGEM, and most common cloning vectors. Compatible with most E. coli strains. Incompatible with p15A-based plasmids — cannot co-transform with pACYC-based vectors.",
    seq: "ATGAAATCTAACAATGCGCTCATCGTCATCCTCGGCACCGTCACCCTGGATGCTGTAGGCATAGGCTTGGTTATGCCGGTACTGCCGGGCCTCTTGCGGGATATCGTCCATTCCGACAGCATCGCCAGTCACTATGGCGTGCTGCTAGCGCTATATGCGTTGATGCAATTTCTATGCGCACCCGTTCTCGGAGCACTGTCCGACCGCTTTGGCCGCCGCCCAGTCCTGCTCGCTTCGCTACTTGGAGCCACTATCGACTACGCGATCATGGCGACCACACCCGTCCTGTGGATCCTCTACGCCGGACGCATCGTGGCCGGCATCACCGGCGCCACAGGTGCGGTTGCTGGCGCCTATATCGCCGACATCACCGATGGGGAAGATCGGGCTCGCCACTTCGGGCTCATGAGCGCTTGTTTCGGCGTGGGTATGGTGGCAGGCCCCGTGGCCGGGGGACTGTTGGGCGCCATCTCCTTGCATGCACCATTCCTTGCGGCGGCGGTGCTCAACGGCCTCAACCTACTACTGGGCTGCTTCCTAATGCAGGAGTCGCATAAGGGAGAGCGTCGACCGATGCCCTTGAGAGCCTTCAACCCAGTCAGCTCCTTCCGGTGGGCGCGGGGCATGACTATCGTCGCCGCACTTATGACTGTCTTCTTTATCATGCAACTCGTAGGACAGGTGCCGGCAGCGCTCTGGGTCATTTTCGGCGAGGACCGCTTTCGCTGGAGCGCGACGATGATCGGCCTGTCGCTTGCGGTATTCGGAATCTTGCACGCCCTCGCTCAAGCCTTCGTCACTGGTCCCGCCACCAAACGTTTCGGCGAGAAGCAGGCCATTATCGCCGGCATGGCGGCCGACGCGCTGGGCTACGTCTTGCTGGCGTTCGCGACGCGAGGCTGGATGGCCTTCCCCATTATGATTCTTCTCGCTTCCGGCGGCATCGGGATGCCCGCGTTGCAGGCCATGCTGTCCAGGCAGGTAGATGACGACCATCAGGGACAGCTTCAAGGATCGCTCGCGGCTCTTACCAGCCTAACTTCGATCACTGGACCGCTGATCGTCACGGCGATTTATGCCGCCTCGGCGAGCACATGGAACGGGTTGGCATGGATTGTAGGCGCCGCCCTATACCTTGTCTGCCTCCCCGCGTTGCGTCGCGGTGCATGGAGCCGGGCCACCTCGACCTGA",
    copyNumber: 500,
    source: "features.json: ColE1 ori (1191 bp) from SnapGene plasmid library",
  },
  {
    id: "p15a_ori",
    name: "p15A origin",
    type: "ori",
    organisms: ["ecoli"],
    description:
      "Medium-copy origin (~15-20 copies/cell) from pACYC184. Compatible with ColE1 plasmids — use when you need to co-transform two plasmids. Found in pACYC, pZA, and many two-plasmid systems.",
    seq: "TTGAGATCGTTTTGGTCTGCGCGTAATCTCTTGCTCTGAAAACGAAAAAACCGCCTTGCAGGGCGGTTTTTCGAAGGTTCTCTGAGCTACCAACTCTTTGAACCGAGGTAACTGGCTTGGAGGAGCGCAGTCACCAAAACTTGTCCTTTCAGTTTAGCCTTAACCGGCGCATGACTTCAAGACTAACTCCTCTAAATCAATTACCAGTGGCTGCTGCCAGTGGTGCTTTTGCATGTCTTTCCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGACTGAACGGGGGGTTCGTGCATACAGTCCAGCTTGGAGCGAACTGCCTACCCGGAACTGAGTGTCAGGCGTGGAATGAGACAAACGCGGCCATAACAGCGGAATGACACCGGTAAACCGAAAGGCAGGAACAGGAGAGCGCACGAGGGAGCCGCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCACTGATTTGAGCGTCAGATTTCGTGATGCTTGTCAGGGGGGCGGAGCCTATGGAAA",
    copyNumber: 20,
    source: "features.json: p15A ori (546 bp) from SnapGene plasmid library",
  },

  // ── CDS Library — fluorescent reporters, enzymes, genome editing ──────────

  {
    id: "egfp_cds",
    name: "EGFP",
    type: "cds",
    organisms: ["ecoli", "mammalian", "yeast"],
    description:
      "Enhanced Green Fluorescent Protein (720 bp). The standard green fluorescent reporter. Use for live-cell imaging, protein localization, or expression monitoring. Excitation 488 nm, emission 507 nm. Works in E. coli, yeast, and mammalian cells.",
    seq: "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA",
    source: "features.json[5451]: EGFP 720 bp",
  },
  {
    id: "mvenus_cds",
    name: "mVenus",
    type: "cds",
    organisms: ["ecoli", "mammalian", "yeast"],
    description:
      "mVenus yellow fluorescent protein (723 bp). Brightest monomeric yellow FP. Excitation 515 nm, emission 528 nm. Good alternative to EGFP when spectral separation from blue/cyan FPs is needed.",
    seq: "ATGGTGAGCAAAGGCGAAGAACTGTTTACCGGCGTGGTGCCGATTCTGGTGGAACTGGATGGCGATGTGAACGGCCATAAATTTAGCGTGAGCGGCGAAGGCGAAGGCGATGCGACCTATGGCAAACTGACCCTGAAACTGATTTGCACCACCGGCAAACTGCCGGTGCCGTGGCCGACCCTGGTGACCACCCTGGGCTATGGCCTGCAATGCTTTGCGCGCTATCCGGATCATATGAAACAGCATGATTTTTTTAAAAGCGCGATGCCGGAAGGCTATGTGCAGGAACGCACCATTTTTTTTAAAGATGATGGCAACTATAAAACCCGCGCGGAAGTGAAATTTGAAGGCGATACCCTGGTGAACCGCATTGAACTGAAAGGCATTGATTTTAAAGAAGATGGCAACATTCTGGGCCATAAACTGGAATATAACTATAACAGCCATAACGTGTATATTACCGCGGATAAACAGAAAAACGGCATTAAAGCGAACTTTAAAATTCGCCATAACATTGAAGATGGCGGCGTGCAGCTGGCGGATCATTATCAGCAGAACACCCCGATTGGCGATGGCCCGGTGCTGCTGCCGGATAACCATTATCTGAGCTATCAGAGCGCGCTGAGCAAAGATCCGAACGAAAAACGCGATCATATGGTGCTGCTGGAATTTGTGACCGCGGCGGGCATTACCCTGGGCATGGATGAACTGTATAAATAATAA",
    source: "features.json[5932]: mVenus 723 bp",
  },
  {
    id: "tdtomato_cds",
    name: "tdTomato",
    type: "cds",
    organisms: ["ecoli", "mammalian", "yeast"],
    description:
      "tdTomato tandem-dimer red fluorescent protein (1431 bp). One of the brightest red FPs available. Excitation 554 nm, emission 581 nm. Tandem dimer — stays monomeric in cells but slightly larger than mCherry.",
    seq: "ATGGTGAGCAAGGGCGAGGAGGTCATCAAAGAGTTCATGCGCTTCAAGGTGCGCATGGAGGGCTCCATGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGCGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCCCAGTTCATGTACGGCTCCAAGGCGTACGTGAAGCACCCCGCCGACATCCCCGATTACAAGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGTCTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCACGCTGATCTACAAGGTGAAGATGCGCGGCACCAACTTCCCCCCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCACCGAGCGCCTGTACCCCCGCGACGGCGTGCTGAAGGGCGAGATCCACCAGGCCCTGAAGCTGAAGGACGGCGGCCACTACCTGGTGGAGTTCAAGACCATCTACATGGCCAAGAAGCCCGTGCAACTGCCCGGCTACTACTACGTGGACACCAAGCTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAGCGCTCCGAGGGCCGCCACCACCTGTTCCTGGGGCATGGCACCGGCAGCACCGGCAGCGGCAGCTCCGGCACCGCCTCCTCCGAGGACAACAACATGGCCGTCATCAAAGAGTTCATGCGCTTCAAGGTGCGCATGGAGGGCTCCATGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGCGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCCCAGTTCATGTACGGCTCCAAGGCGTACGTGAAGCACCCCGCCGACATCCCCGATTACAAGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGTCTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCACGCTGATCTACAAGGTGAAGATGCGCGGCACCAACTTCCCCCCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCACCGAGCGCCTGTACCCCCGCGACGGCGTGCTGAAGGGCGAGATCCACCAGGCCCTGAAGCTGAAGGACGGCGGCCACTACCTGGTGGAGTTCAAGACCATCTACATGGCCAAGAAGCCCGTGCAACTGCCCGGCTACTACTACGTGGACACCAAGCTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAGCGCTCCGAGGGCCGCCACCACCTGTTCCTGTACGGCATGGACGAGCTGTACAAGTAG",
    source: "features.json[6264]: tdTomato 1431 bp",
  },
  {
    id: "luc_cds",
    name: "Firefly luciferase",
    type: "cds",
    organisms: ["ecoli", "mammalian", "yeast"],
    description:
      "Firefly luciferase (luc+, 1653 bp). Bioluminescent reporter — produces light from luciferin + ATP. Use for reporter assays, promoter activity studies, or in vivo imaging. Sensitive: detectable at very low expression levels. Pair with Renilla luciferase (rluc_cds) for dual-reporter normalization.",
    seq: "ATGGAAGATGCCAAAAACATTAAGAAGGGCCCAGCGCCATTCTACCCACTCGAAGACGGGACCGCCGGCGAGCAGCTGCACAAAGCCATGAAGCGCTACGCCCTGGTGCCCGGCACCATCGCCTTTACCGACGCACATATCGAGGTGGACATTACCTACGCCGAGTACTTCGAGATGAGCGTTCGGCTGGCAGAAGCTATGAAGCGCTATGGGCTGAATACAAACCATCGGATCGTGGTGTGCAGCGAGAATAGCTTGCAGTTCTTCATGCCCGTGTTGGGTGCCCTGTTCATCGGTGTGGCTGTGGCCCCAGCTAACGACATCTACAACGAGCGCGAGCTGCTGAACAGCATGGGCATCAGCCAGCCCACCGTCGTATTCGTGAGCAAGAAAGGGCTGCAAAAGATCCTCAACGTGCAAAAGAAGCTACCGATCATACAAAAGATCATCATCATGGATAGCAAGACCGACTACCAGGGCTTCCAAAGCATGTACACCTTCGTGACTTCCCATTTGCCACCCGGCTTCAACGAGTACGACTTCGTGCCCGAGAGCTTCGACCGGGACAAAACCATCGCCCTGATCATGAACAGTAGTGGCAGTACCGGATTGCCCAAGGGCGTAGCCCTACCGCACCGCACCGCTTGTGTCCGATTCAGTCATGCCCGCGACCCCATCTTCGGCAACCAGATCATCCCCGACACCGCTATCCTCAGCGTGGTGCCATTTCACCACGGCTTCGGCATGTTCACCACGCTGGGCTACTTGATCTGCGGCTTTCGGGTCGTGCTCATGTACCGCTTCGAGGAGGAGCTATTCTTGCGCAGCTTGCAAGACTATAAGATTCAATCTGCCCTGCTGGTGCCCACACTATTTAGCTTCTTCGCTAAGAGCACTCTCATCGACAAGTACGACCTAAGCAACTTGCACGAGATCGCCAGCGGCGGGGCGCCGCTCAGCAAGGAGGTAGGTGAGGCCGTGGCCAAACGCTTCCACCTACCAGGCATCCGCCAGGGCTACGGCCTGACAGAAACAACCAGCGCCATTCTGATCACCCCCGAAGGGGACGACAAGCCTGGCGCAGTAGGCAAGGTGGTGCCCTTCTTCGAGGCTAAGGTGGTGGACTTGGACACCGGTAAGACACTGGGTGTGAACCAGCGCGGCGAGCTGTGCGTCCGTGGCCCCATGATCATGAGCGGCTACGTTAACAACCCCGAGGCTACAAACGCTCTCATCGACAAGGACGGCTGGCTGCACAGCGGCGACATCGCCTACTGGGACGAGGACGAGCACTTCTTCATCGTGGACCGGCTGAAGAGCCTGATCAAATACAAGGGCTACCAGGTAGCCCCAGCCGAACTGGAGAGCATCCTGCTGCAACACCCCAACATCTTCGACGCCGGGGTCGCCGGCCTGCCCGACGACGATGCCGGCGAGCTGCCCGCCGCAGTCGTCGTGCTGGAACACGGTAAAACCATGACCGAGAAGGAGATCGTGGACTATGTGGCCAGCCAGGTTACAACCGCCAAGAAGCTGCGCGGTGGTGTTGTGTTCGTGGACGAGGTGCCTAAAGGACTGACCGGCAAGTTGGACGCCCGCAAGATCCGCGAGATTCTCATTAAGGCCAAGAAGGGCGGCAAGATCGCCGTGTAA",
    source: "features.json[79]: luciferase 1653 bp",
  },
  {
    id: "rluc_cds",
    name: "Renilla luciferase",
    type: "cds",
    organisms: ["ecoli", "mammalian", "yeast"],
    description:
      "Renilla luciferase (Rluc, 936 bp). Smaller bioluminescent reporter using coelenterazine as substrate. Spectrally distinct from firefly luciferase — use alongside luc_cds for dual-reporter normalization assays where one reporter measures experimental output and the other measures transfection efficiency.",
    seq: "ATGGCTTCCAAGGTGTACGACCCCGAGCAACGCAAACGCATGATCACTGGGCCTCAGTGGTGGGCTCGCTGCAAGCAAATGAACGTGCTGGACTCCTTCATCAACTACTATGATTCCGAGAAGCACGCCGAGAACGCCGTGATTTTTCTGCATGGTAACGCTGCCTCCAGCTACCTGTGGAGGCACGTCGTGCCTCACATCGAGCCCGTGGCTAGATGCATCATCCCTGATCTGATCGGAATGGGTAAGTCCGGCAAGAGCGGGAATGGCTCATATCGCCTCCTGGATCACTACAAGTACCTCACCGCTTGGTTCGAGCTGCTGAACCTTCCAAAGAAAATCATCTTTGTGGGCCACGACTGGGGGGCTTGTCTGGCCTTTCACTACTCCTACGAGCACCAAGACAAGATCAAGGCCATCGTCCATGCTGAGAGTGTCGTGGACGTGATCGAGTCCTGGGACGAGTGGCCTGACATCGAGGAGGATATCGCCCTGATCAAGAGCGAAGAGGGCGAGAAAATGGTGCTTGAGAATAACTTCTTCGTCGAGACCATGCTCCCAAGCAAGATCATGCGGAAACTGGAGCCTGAGGAGTTCGCTGCCTACCTGGAGCCATTCAAGGAGAAGGGCGAGGTTAGACGGCCTACCCTCTCCTGGCCTCGCGAGATCCCTCTCGTTAAGGGAGGCAAGCCCGACGTCGTCCAGATTGTCCGCAACTACAACGCCTACCTTCGGGCCAGCGACGATCTGCCTAAGATGTTCATCGAGTCCGACCCTGGGTTCTTTTCCAACGCTATTGTCGAGGGAGCTAAGAAGTTCCCTAACACCGAGTTCGTGAAGGTGAAGGGCCTCCACTTCAGCCAGGAGGACGCTCCAGATGAAATGGGTAAGTACATCAAGAGCTTCGTGGAGCGCGTGCTGAAGAACGAGCAGTAA",
    source: "features.json[6071]: Renilla luciferase 936 bp",
  },
  {
    id: "gst_cds",
    name: "GST tag",
    type: "cds",
    organisms: ["ecoli"],
    description:
      "Glutathione S-transferase affinity tag (657 bp). Fuse to N-terminus of your protein for one-step glutathione-Sepharose purification. GST tag (~26 kDa) improves solubility of many recombinant proteins. Cleavable with thrombin or PreScission protease. Used in pGEX vector series.",
    seq: "ATGTCCCCTATACTAGGTTATTGGAAAATTAAGGGCCTTGTGCAACCCACTCGACTTCTTTTGGAATATCTTGAAGAAAAATATGAAGAGCATTTGTATGAGCGCGATGAAGGTGATAAATGGCGAAACAAAAAGTTTGAATTGGGTTTGGAGTTTCCCAATCTTCCTTATTATATTGATGGTGATGTTAAATTAACACAGTCTATGGCCATCATACGTTATATAGCTGACAAGCACAACATGTTGGGTGGTTGTCCAAAAGAGCGTGCAGAGATTTCAATGCTTGAAGGAGCGGTTTTGGATATTAGATACGGTGTTTCGAGAATTGCATATAGTAAAGACTTTGAAACTCTCAAAGTTGATTTTCTTAGCAAGCTACCTGAAATGCTGAAAATGTTCGAAGATCGTTTATGTCATAAAACATATTTAAATGGTGATCATGTAACCCATCCTGACTTCATGTTGTATGACGCTCTTGATGTTGTTTTATACATGGACCCAATGTGCCTGGATGCGTTCCCAAAATTAGTTTGTTTTAAAAAACGTATTGAAGCTATCCCACAAATTGATAAGTACTTGAAATCCAGCAAGTATATAGCATGGCCTTTGCAGGGCTGGCAAGCCACGTTTGGTGGTGGCGACCATCCTCCAAAATAA",
    source: "features.json[5628]: GST tag 657 bp",
  },
  {
    id: "cjcas9_cds",
    name: "CjCas9",
    type: "cds",
    organisms: ["ecoli", "mammalian"],
    description:
      "Campylobacter jejuni Cas9 (CjCas9, 1323 bp). The smallest functional Cas9 — fits in AAV vectors (capacity ~4.7 kb). Uses a unique PAM (5'-NNNNRYAC-3') that is less frequent than SpCas9 NGG. Best for delivery-constrained applications: AAV gene therapy, in vivo editing. Requires a CjCas9-compatible sgRNA scaffold.",
    seq: "ATGAATCCAAGCCAAATACTTGAAAATTTAAAAAAAGAATTAAGTGAAAACGAATACGAAAACTATTTATCAAATTTAAAATTCAACGAAAAACAAAGCAAAGCAGATCTTTTAGTTTTTAATGCTCCAAATGAACTCATGGCTAAATTCATACAAACAAAATACGGCAAAAAAATCGCGCATTTTTATGAAGTGCAAAGCGGAAATAAAGCCATCATAAATATACAAGCACAAAGTGCTAAACAAAGCAACAAAAGCACAAAAATCGACATAGCTCATATAAAAGCACAAAGCACGATTTTAAATCCTTCTTTTACTTTTGAAAGTTTTGTTGTAGGGGATTCTAACAAATACGCTTATGGAGCATGTAAAGCCATAGCACATAAAGACAAACTTGGAAAACTTTATAATCCAATCTTTGTTTATGGACCTACAGGACTTGGAAAAACACATTTACTTCAAGCAGTTGGAAATGCAAGCTTAGAAATGGGAAAAAAAGTTATTTACGCTACCAGTGAAAATTTCATCAACGATTTTACTTCAAATTTAAAAAATGGTTCTTTAGATAAATTTCATGAAAAGTATAGAAACTGCGATGTTTTACTTATAGATGATGTACAGTTTTTAGGAAAAACCGATAAAATTCAAGAAGAATTTTTCTTTATATTTAATGAAATCAAAAATAACGATGGACAAATCATCATGACTTCAGACAATCCACCCAACATGCTAAAAGGTATAACCGAACGCTTAAAAAGTCGTTTTGCACATGGGATCATAGCTGATATAACTCCACCTCAACTAGATACAAAAATAGCCATCATAAGAAAAAAATGTGAATTTAACGATATCAATCTTTCTAATGATATTATAAACTATATCGCTACTTCTTTAGGGGATAATATAAGAGAAATCGAAGGTATCATCATAAGTTTAAATGCTTATGCAACCATACTAGGACAAGAAATCACACTCGAACTTGCCAAAAGTGTGATGAAAGATCATATCAAAGAAAAGAAAGAAAATATCACTATAGATGACATTTTATCTTTGGTATGTAAAGAATTTAACATCAAACCAAGCGATGTGAAATCCAATAAAAAAACTCAAAATATAGTCACAGCAAGACGCATTGTGATTTACCTAGCTAGGGCACTTACGGCTTTGACTATGCCACAACTTGCGAATTATTTTGAAATGAAAGATCATACAGCTATTTCACATAATGTTAAAAAAATCACAGAAATGATAGAAAATGATGCTTCTTTAAAAGCAAAAATCGAAGAACTTAAAAACAAAATTCTTGTTAAAAGTCAAAGTTAA",
    source: "features.json[5279]: CjCas9 1323 bp",
  },
  {
    id: "spcas9_cds",
    name: "SpCas9",
    type: "cds",
    organisms: ["ecoli", "mammalian"],
    description:
      "Streptococcus pyogenes Cas9 (SpCas9, 4107 bp). The standard CRISPR-Cas9 nuclease. Uses NGG PAM — the most widely used system with the most published protocols and guide RNA resources. Too large for standard AAV delivery — use CjCas9 (1323 bp) for AAV applications.",
    seq: "ATGGATAAGAAATACTCAATAGGCTTAGATATCGGCACAAATAGCGTCGGATGGGCGGTGATCACTGATGAATATAAGGTTCCGTCTAAAAAGTTCAAGGTTCTGGGAAATACAGACCGCCACAGTATCAAAAAAAATCTTATAGGGGCTCTTTTATTTGACAGTGGAGAGACAGCGGAAGCGACTCGTCTCAAACGGACAGCTCGTAGAAGGTATACACGTCGGAAGAATCGTATTTGTTATCTACAGGAGATTTTTTCAAATGAGATGGCGAAAGTAGATGATAGTTTCTTTCATCGACTTGAAGAGTCTTTTTTGGTGGAAGAAGACAAGAAGCATGAACGTCATCCTATTTTTGGAAATATAGTAGATGAAGTTGCTTATCATGAGAAATATCCAACTATCTATCATCTGCGAAAAAAATTGGTAGATTCTACTGATAAAGCGGATTTGCGCTTAATCTATTTGGCCTTAGCGCATATGATTAAGTTTCGTGGTCATTTTTTGATTGAGGGAGATTTAAATCCTGATAATAGTGATGTGGACAAACTATTTATCCAGTTGGTACAAACCTACAATCAATTATTTGAAGAAAACCCTATTAACGCAAGTGGAGTAGATGCTAAAGCGATTCTTTCTGCACGATTGAGTAAATCAAGACGATTAGAAAATCTCATTGCTCAGCTCCCCGGTGAGAAGAAAAATGGCTTATTTGGGAATCTCATTGCTTTGTCATTGGGTTTGACCCCTAATTTTAAATCAAATTTTGATTTGGCAGAAGATGCTAAATTACAGCTTTCAAAAGATACTTACGATGATGATTTAGATAATTTATTGGCGCAAATTGGAGATCAATATGCTGATTTGTTTTTGGCAGCTAAGAATTTATCAGATGCTATTTTACTTTCAGATATCCTAAGAGTAAATACTGAAATAACTAAGGCTCCCCTATCAGCTTCAATGATTAAACGCTACGATGAACATCATCAAGACTTGACTCTTTTAAAAGCTTTAGTTCGACAACAACTTCCAGAAAAGTATAAAGAAATCTTTTTTGATCAATCAAAAAACGGATATGCAGGTTATATTGATGGGGGAGCTAGCCAAGAAGAATTTTATAAATTTATCAAACCAATTTTAGAAAAAATGGATGGTACTGAGGAATTATTGGTGAAACTAAATCGTGAAGATTTGCTGCGCAAGCAACGGACCTTTGACAACGGCTCTATTCCCCATCAAATTCACTTGGGTGAGCTGCATGCTATTTTGAGAAGACAAGAAGACTTTTATCCATTTTTAAAAGACAATCGTGAGAAGATTGAAAAAATCTTGACTTTTCGAATTCCTTATTATGTTGGTCCATTGGCGCGTGGCAATAGTCGTTTTGCATGGATGACTCGGAAGTCTGAAGAAACAATTACCCCATGGAATTTTGAAGAAGTTGTCGATAAAGGTGCTTCAGCTCAATCATTTATTGAACGCATGACAAACTTTGATAAAAATCTTCCAAATGAAAAAGTACTACCAAAACATAGTTTGCTTTATGAGTATTTTACGGTTTATAACGAATTGACAAAGGTCAAATATGTTACTGAAGGAATGCGAAAACCAGCATTTCTTTCAGGTGAACAGAAGAAAGCCATTGTTGATTTACTCTTCAAAACAAATCGAAAAGTAACCGTTAAGCAATTAAAAGAAGATTATTTCAAAAAAATAGAATGTTTTGATAGTGTTGAAATTTCAGGAGTTGAAGATAGATTTAATGCTTCATTAGGTACCTACCATGATTTGCTAAAAATTATTAAAGATAAAGATTTTTTGGATAATGAAGAAAATGAAGATATCTTAGAGGATATTGTTTTAACATTGACCTTATTTGAAGATAGGGAGATGATTGAGGAAAGACTTAAAACATATGCTCACCTCTTTGATGATAAGGTGATGAAACAGCTTAAACGTCGCCGTTATACTGGTTGGGGACGTTTGTCTCGAAAATTGATTAATGGTATTAGGGATAAGCAATCTGGCAAAACAATATTAGATTTTTTGAAATCAGATGGTTTTGCCAATCGCAATTTTATGCAGCTGATCCATGATGATAGTTTGACATTTAAAGAAGACATTCAAAAAGCACAAGTGTCTGGACAAGGCGATAGTTTACATGAACATATTGCAAATTTAGCTGGTAGCCCTGCTATTAAAAAAGGTATTTTACAGACTGTAAAAGTTGTTGATGAATTGGTCAAAGTAATGGGGCGGCATAAGCCAGAAAATATCGTTATTGAAATGGCACGTGAAAATCAGACAACTCAAAAGGGCCAGAAAAATTCGCGAGAGCGTATGAAACGAATCGAAGAAGGTATCAAAGAATTAGGAAGTCAGATTCTTAAAGAGCATCCTGTTGAAAATACTCAATTGCAAAATGAAAAGCTCTATCTCTATTATCTCCAAAATGGAAGAGACATGTATGTGGACCAAGAATTAGATATTAATCGTTTAAGTGATTATGATGTCGATCACATTGTTCCACAAAGTTTCCTTAAAGACGATTCAATAGACAATAAGGTCTTAACGCGTTCTGATAAAAATCGTGGTAAATCGGATAACGTTCCAAGTGAAGAAGTAGTCAAAAAGATGAAAAACTATTGGAGACAACTTCTAAACGCCAAGTTAATCACTCAACGTAAGTTTGATAATTTAACGAAAGCTGAACGTGGAGGTTTGAGTGAACTTGATAAAGCTGGTTTTATCAAACGCCAATTGGTTGAAACTCGCCAAATCACTAAGCATGTGGCACAAATTTTGGATAGTCGCATGAATACTAAATACGATGAAAATGATAAACTTATTCGAGAGGTTAAAGTGATTACCTTAAAATCTAAATTAGTTTCTGACTTCCGAAAAGATTTCCAATTCTATAAAGTACGTGAGATTAACAATTACCATCATGCCCATGATGCGTATCTAAATGCCGTCGTTGGAACTGCTTTGATTAAGAAATATCCAAAACTTGAATCGGAGTTTGTCTATGGTGATTATAAAGTTTATGATGTTCGTAAAATGATTGCTAAGTCTGAGCAAGAAATAGGCAAAGCAACCGCAAAATATTTCTTTTACTCTAATATCATGAACTTCTTCAAAACAGAAATTACACTTGCAAATGGAGAGATTCGCAAACGCCCTCTAATCGAAACTAATGGGGAAACTGGAGAAATTGTCTGGGATAAAGGGCGAGATTTTGCCACAGTGCGCAAAGTATTGTCCATGCCCCAAGTCAATATTGTCAAGAAAACAGAAGTACAGACAGGCGGATTCTCCAAGGAGTCAATTTTACCAAAAAGAAATTCGGACAAGCTTATTGCTCGTAAAAAAGACTGGGATCCAAAAAAATATGGTGGTTTTGATAGTCCAACGGTAGCTTATTCAGTCCTAGTGGTTGCTAAGGTGGAAAAAGGGAAATCGAAGAAGTTAAAATCCGTTAAAGAGTTACTAGGGATCACAATTATGGAAAGAAGTTCCTTTGAAAAAAATCCGATTGACTTTTTAGAAGCTAAAGGATATAAGGAAGTTAAAAAAGACTTAATCATTAAACTACCTAAATATAGTCTTTTTGAGTTAGAAAACGGTCGTAAACGGATGCTGGCTAGTGCCGGAGAATTACAAAAAGGAAATGAGCTGGCTCTGCCAAGCAAATATGTGAATTTTTTATATTTAGCTAGTCATTATGAAAAGTTGAAGGGTAGTCCAGAAGATAACGAACAAAAACAATTGTTTGTGGAGCAGCATAAGCATTATTTAGATGAGATTATTGAGCAAATCAGTGAATTTTCTAAGCGTGTTATTTTAGCAGATGCCAATTTAGATAAAGTTCTTAGTGCATATAACAAACATAGAGACAAACCAATACGTGAACAAGCAGAAAATATTATTCATTTATTTACGTTGACGAATCTTGGAGCTCCCGCTGCTTTTAAATATTTTGATACAACAATTGATCGTAAACGATATACGTCTACAAAAGAAGTTTTAGATGCCACTCTTATCCATCAATCCATCACTGGTCTTTATGAAACACGCATTGATTTGAGTCAGCTAGGAGGTGACTGA",
    source: "features.json[6217]: SpCas9 4107 bp",
  },

  // ── Resistance Markers ─────────────────────────────────────────────────────

  {
    id: "ampR_marker",
    name: "AmpR (ampicillin resistance)",
    type: "marker",
    organisms: ["ecoli"],
    description:
      "Beta-lactamase cassette conferring ampicillin resistance. Includes native AmpR promoter + bla CDS. Most common selection marker. Caution: ampicillin degrades in culture — satellite colonies can appear after 12-16h of growth. Prefer KanR for long cultures or when false-positive colonies are a concern.",
    seq: "CGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTGTTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGCAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA",
    source: "features.json: AmpR promoter (105 bp) + AmpR/bla CDS (861 bp, TEM-1) = 966 bp",
  },
  {
    id: "kanR_marker",
    name: "KanR (kanamycin resistance)",
    type: "marker",
    organisms: ["ecoli"],
    description:
      "Aminoglycoside phosphotransferase cassette conferring kanamycin resistance. Kanamycin is stable in culture — no satellite colonies. Preferred when working with high-copy plasmids or extended culture times. Uses AmpR promoter to drive KanR CDS expression.",
    seq: "CGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATTGAAAAAGGAAGAGTATGAGCCATATTCAACGGGAAACGTCTTGCTCGAGGCCGCGATTAAATTCCAACATGGATGCTGATTTATATGGGTATAAATGGGCTCGCGATAATGTCGGGCAATCAGGTGCGACAATCTATCGATTGTATGGGAAGCCCGATGCGCCAGAGTTGTTTCTGAAACATGGCAAAGGTAGCGTTGCCAATGATGTTACAGATGAGATGGTCAGGCTAAACTGGCTGACGGAATTTATGCCTCTTCCGACCATCAAGCATTTTATCCGTACTCCTGATGATGCATGGTTACTCACCACTGCGATCCCAGGGAAAACAGCATTCCAGGTATTAGAAGAATATCCTGATTCAGGTGAAAATATTGTTGATGCGCTGGCAGTGTTCCTGCGCCGGTTGCATTCGATTCCTGTTTGTAATTGTCCTTTTAACGGCGATCGCGTATTTCGTCTCGCTCAGGCGCAATCACGAATGAATAACGGTTTGGTTGGTGCGAGTGATTTTGATGACGAGCGTAATGGCTGGCCTGTTGAACAAGTCTGGAAAGAAATGCATAAGCTTTTGCCATTCTCACCGGATTCAGTCGTCACTCATGGTGATTTCTCACTTGATAACCTTATTTTTGACGAGGGGAAATTAATAGGTTGTATTGATGTTGGACGAGTCGGAATCGCAGACCGATACCAGGATCTTGCCATCCTATGGAACTGCCTCGGTGAGTTTTCTCCTTCATTACAGAAACGGCTTTTTCAAAAATATGGTATTGATAATCCTGATATGAATAAATTGCAGTTTCACTTGATGCTCGATGAGTTTTTCTGA",
    source: "features.json: AmpR promoter (105 bp) + KanR/APH(3')-Ia CDS (816 bp, Tn903) = 921 bp",
  },

  // ── Mammalian promoters ────────────────────────────────────────────────────

  {
    id: "cmv_promoter",
    name: "CMV promoter",
    type: "promoter",
    organisms: ["mammalian"],
    description:
      "Human cytomegalovirus (CMV) immediate early promoter. Strongest constitutive promoter for mammalian cells — works in virtually all mammalian cell lines (HEK293, CHO, HeLa, COS, NIH3T3). First choice for high-level transient or stable mammalian expression.",
    seq: "GTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTGACTCACGGGGATTTCCAAGTCTCCACCCCATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCAAAATGTCGTAACAACTCCGCCCCATTGACGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCT",
    strength: "strong",
    source: "features.json[43]: CMV promoter (204 bp)",
  },
  {
    id: "sv40_promoter",
    name: "SV40 early promoter",
    type: "promoter",
    organisms: ["mammalian"],
    description:
      "SV40 early promoter. Moderate, constitutive expression in most mammalian cell lines. Commonly used to drive selection marker genes (NeoR, PuroR) within mammalian expression vectors. Weaker than CMV but reliable.",
    seq: "GTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAA",
    strength: "medium",
    source: "features.json[7]: SV40 promoter (331 bp)",
  },

  // ── Mammalian RBS (Kozak) ─────────────────────────────────────────────────

  {
    id: "kozak",
    name: "Kozak sequence",
    type: "rbs",
    organisms: ["mammalian"],
    description:
      "Kozak consensus sequence (GCCACC) immediately preceding the ATG start codon. Required for efficient translation initiation in mammalian cells. Always place directly before the INSERT's ATG. No prokaryotic Shine-Dalgarno RBS is needed for mammalian expression.",
    seq: "GCCACC",
    source: "Kozak consensus (Kozak 1987, J. Mol. Biol.)",
  },

  // ── Mammalian polyA signals (terminators) ─────────────────────────────────

  {
    id: "bgh_polya",
    name: "bGH poly(A) signal",
    type: "terminator",
    organisms: ["mammalian"],
    description:
      "Bovine growth hormone (bGH) polyadenylation signal. Standard terminator for mammalian expression vectors — provides efficient transcriptional termination and mRNA 3' processing. Widely used in pCDNA3, pLenti, and most commercial mammalian vectors. Pair with CMV promoter.",
    seq: "CTGTGCCTTCTAGTTGCCAGCCATCTGTTGTTTGCCCCTCCCCCGTGCCTTCCTTGACCCTGGAAGGTGCCACTCCCACTGTCCTTTCCTAATAAAATGAGGAAATTGCATC",
    source: "features.json[520]: bGH poly(A) signal (112 bp)",
  },
  {
    id: "sv40_polya",
    name: "SV40 poly(A) signal",
    type: "terminator",
    organisms: ["mammalian"],
    description:
      "SV40 polyadenylation signal. Efficient transcriptional terminator for mammalian expression, commonly used to terminate selection marker expression cassettes within the same vector. Use bGH poly(A) for the gene of interest and SV40 poly(A) for the selection marker.",
    seq: "AACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTA",
    source: "features.json[11]: SV40 poly(A) signal (122 bp)",
  },

  // ── Mammalian origins ──────────────────────────────────────────────────────

  {
    id: "sv40_ori",
    name: "SV40 ori",
    type: "ori",
    organisms: ["mammalian"],
    description:
      "SV40 origin of replication. Enables episomal replication in COS-1 and COS-7 cells (which express SV40 large T antigen). Not required for stable integration — use only when episomal replication in COS cells is desired for transient high-level expression. All mammalian vectors still require a ColE1 ori for bacterial propagation.",
    seq: "GGCCTCCAAAAAAGCCTCCTCACTACTTCTGGAATAGCTCAGAGGCAGAGGCGGCCTCGGCCTCTGCATAAATAAAAAAAATTAGTCAGCCATGGGGCGGAGAATGGGCGGAACTGGGCGGAGTTAGGGGCGGGAT",
    source: "features.json[8]: SV40 ori (136 bp)",
  },

  // ── Mammalian selection markers (complete cassettes with promoter + polyA) ─

  {
    id: "neoR_mammalian",
    name: "NeoR/G418 resistance (mammalian)",
    type: "marker",
    organisms: ["mammalian"],
    description:
      "Complete neomycin/G418 resistance cassette for mammalian stable selection: SV40 promoter + NeoR/APH(3')-Ia CDS + SV40 poly(A). Select with 400-800 μg/mL G418 (Geneticin). Slower selection (~2-3 weeks) than puromycin but broadly used. The same NeoR gene also confers kanamycin resistance in E. coli.",
    seq: "GTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAAATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAAGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAACATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGAGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAACTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGAAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTA",
    source: "features.json: SV40 promoter (331 bp) + NeoR CDS (795 bp) + SV40 polyA (122 bp) = 1248 bp",
  },
  {
    id: "puroR_mammalian",
    name: "PuroR (puromycin resistance, mammalian)",
    type: "marker",
    organisms: ["mammalian"],
    description:
      "Complete puromycin resistance cassette for mammalian stable selection: SV40 promoter + PuroR CDS + SV40 poly(A). Select with 1-10 μg/mL puromycin. Fastest mammalian selection marker — resistant colonies appear in 2-5 days. Preferred for generating stable cell lines quickly. Lethal to non-resistant cells within 48h.",
    seq: "GTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAAATGACCGAGTACAAGCCTACCGTGCGCCTGGCCACTCGCGATGATGTGCCCCGCGCCGTCCGCACTCTGGCCGCCGCTTTCGCCGACTACCCCGCTACCCGGCACACCGTGGACCCCGACCGGCACATCGAGCGTGTGACAGAGTTGCAGGAGCTGTTCCTGACCCGCGTCGGGCTGGACATCGGCAAGGTGTGGGTAGCCGACGACGGCGCGGCCGTGGCCGTGTGGACTACCCCCGAGAGCGTTGAGGCCGGCGCCGTGTTCGCCGAGATCGGCCCCCGAATGGCCGAGCTGAGCGGCAGCCGCCTGGCCGCCCAGCAGCAAATGGAGGGCCTGCTTGCCCCCCATCGTCCCAAGGAGCCTGCCTGGTTTCTGGCCACTGTAGGAGTGAGCCCCGACCACCAGGGCAAGGGCTTGGGCAGCGCCGTCGTGTTGCCCGGCGTAGAGGCCGCCGAACGCGCCGGTGTGCCCGCCTTTCTCGAAACAAGCGCACCAAGAAACCTTCCATTCTACGAGCGCCTGGGCTTCACCGTGACCGCCGATGTCGAGGTGCCCGAGGGACCTAGGACCTGGTGTATGACACGAAAACCTGGCGCCTAAAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTA",
    source: "features.json: SV40 promoter (331 bp) + PuroR CDS (600 bp) + SV40 polyA (122 bp) = 1053 bp",
  },

  // ── Yeast promoters ───────────────────────────────────────────────────────

  {
    id: "gal1_promoter",
    name: "GAL1 promoter",
    type: "promoter",
    organisms: ["yeast"],
    description:
      "S. cerevisiae GAL1 promoter. Strong, tightly regulated, galactose-inducible promoter. Repressed by glucose; induced by switching to galactose or raffinose + galactose media. The standard inducible promoter for yeast expression (pYES2, pGAL series vectors). ~500-fold induction. Best choice when tight off-state is needed or protein is toxic when overexpressed.",
    seq: "CCCCATTATCTTAGCCTAAAAAAACCTTCTCTTTGGAACTTTCAGTAATACGCTTAACTGCTCATTGCTATATTGAAGTACGGATTAGAAGCCGCCGAGCGGGTGACAGCCCTCCGAAGGAAGACTCTCCTCCGTGCGTCCTCGTCTTCACCGGTCGCGTTCCTGAAACGCAGATGTGCCTCGCGCCGCACTGCTCCGAACAATAAAGATTCTACAATACTAGCTTTTATGGTTATGAAGAGGAAAAATTGGCAGTAACCTGGCCCCACAAACCTTCAAATGAACGAATCAAATTAACAACCATAGGATGATAATGCGATTAGTTTTTTAGCCTTATTTCTGGGGTAATTAATCAGCGAAGCGATGATTTTTGATCTATTAACAGATATATAAATGCAAAAACTGCATAACCACTTTAACTAATACTTTCAACATTTTCGGTTTGTATTACTTCTTATTCAAATGTAATAAAAGTATCAACAAAAAATTGTTAATATACCTCTATACTTTAACGTCAAGGAGGAAACTAGACCCGCCGCCACCATGGAG",
    strength: "strong",
    inducibleBy: "galactose",
    source: "features.json[177]: GAL1 (549 bp)",
  },
  {
    id: "tef1_promoter",
    name: "TEF1 promoter",
    type: "promoter",
    organisms: ["yeast"],
    description:
      "S. cerevisiae TEF1 (translation elongation factor 1α) promoter. Strong, constitutive expression in all growth conditions. One of the strongest yeast constitutive promoters. Used in pTEF, pRS vectors. Good for selection markers and high-level constitutive protein production.",
    seq: "CATAGCTTCAAAATGTTTCTACTCCTTTTTTACTCTTCCAGATTTTCTCGGACTCCGCGCATCGCCGTACCACTTCAAAACACCCAAGCACAGCATACTAAATTTCCCCTCTTTCTTCCTCTAGGGTGTCGTTAATTACCCGTACTAAAGGTTTGGAAAAGAAAAAAGAGACCGCCTCGTTTCTTTTTCTTCGTCGAAAAAGGCAATAAAAATTTTTATCACGTTTCTTTTTCTTGAAAATTTTTTTTTTGATTTTTTTCTCTTTCGATGACCTCCCATTGATATTTAAGTTAATAAACGGTCTTCAATTTCTCAAGTTTCAGTTTCATTTTTCTTGTTCTATTACAACTTTTTTTACTTCTTGCTCATTAGAAAGAAAGCATAGCAATCTAATCTAAG",
    strength: "strong",
    source: "features.json[171]: TEF1 promoter (399 bp)",
  },
  {
    id: "adh1_promoter",
    name: "ADH1 promoter",
    type: "promoter",
    organisms: ["yeast"],
    description:
      "S. cerevisiae ADH1 (alcohol dehydrogenase 1) promoter. Moderate constitutive expression. Active in all growth conditions including glucose. Commonly used for moderate-level constitutive yeast expression. Good choice when strong TEF1 overexpression causes growth problems.",
    seq: "CAACTTCTTTTCTTTTTTTTTCTTTTCTCTCTCCCCCGTTGTTGTCTCACCATATCCGCAATGACAAAAAAATGATGGAAGACACTAAAGGAAAAAATTAACGACAAAGACAGCACCAACAGATGTCGTTGTTCCAGAGCTGATGAGGGGTATCTCGAAGCACACGAAACTTTTTCCTTCCTTCATTCACGCACACTACTCTCTAATGAGCAACGGTATACGGCCTTCCTTCCAGTTACTTGAATTTGAAATAAAAAAAAGTTTGCTGTCTTGCTATCAAGTATAAATAGACCTGCAATTATTAATCTTTTGTTTCCTCGTCATTGTTCTCGTTCCCTTTCTTCCTTGTTTCTTTTTCTGCACAATATTTCAAGCTATACCAAGCATACAATCAACT",
    strength: "medium",
    source: "features.json[2882]: ADH1 promoter (397 bp)",
  },

  // ── Yeast terminators ─────────────────────────────────────────────────────

  {
    id: "cyc1_terminator",
    name: "CYC1 terminator",
    type: "terminator",
    organisms: ["yeast"],
    description:
      "S. cerevisiae CYC1 (iso-1-cytochrome c) transcriptional terminator. The standard yeast terminator — efficient mRNA 3' processing and transcriptional termination. Used in pYES, pRS, and virtually all S. cerevisiae expression vectors. Pair with GAL1, TEF1, or ADH1 promoters.",
    seq: "TCATGTAATTAGTTATGTCACGCTTACATTCACGCCCTCCCCCCACATCCGCTCTAACCGAAAAGGAAGGAGTTAGACAACCTGAAGTCTAGGTCCCTATTTATTTTTTTATAGTTATGTTAGTATTAAGAACGTTATTTATATTTCAAATTTTTCTTTTTTTTCTGTACAGACGCGTGTACGCATGTAACATTATACTGAAAACCTTGCTTGAGAAGGTTTTGGGACGCTCGAAGGCTTTAATTTGC",
    source: "features.json[5347]: CYC1 terminator (248 bp)",
  },
  {
    id: "adh1_terminator",
    name: "ADH1 terminator",
    type: "terminator",
    organisms: ["yeast"],
    description:
      "S. cerevisiae ADH1 transcriptional terminator. Efficient yeast terminator, alternative to CYC1. Sometimes used when CYC1 terminator causes read-through in specific construct contexts.",
    seq: "GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTACTCAAGAATAAGAATTTTCGTTTTAAAACCTAAGAGTCACTTTAAAATTTGTATACACTTATTTTTTTTATAACTTATTTAATAATAAAAATCATAAATCATAAGAAATTCGC",
    source: "features.json[250]: ADH1 terminator (166 bp)",
  },

  // ── Yeast origins ──────────────────────────────────────────────────────────

  {
    id: "2mu_ori",
    name: "2μ origin (high-copy yeast)",
    type: "ori",
    organisms: ["yeast"],
    description:
      "S. cerevisiae 2-micron circle origin of replication. High-copy yeast origin: 10-40 copies per cell. Used in episomal yeast expression vectors (pYES2, pESC series) for high-level protein production. Relies on endogenous 2μ circle FLP/REP proteins — requires a yeast host that contains the 2μ circle (standard lab strains do, but petite mutants may not). Unstable without selection.",
    seq: "GATCCAATATCAAAGGAAATGATAGCATTGAAGGATGAGACTAATCCAATTGAGGAGTGGCAGCATATAGAACAGCTAAAGGGTAGTGCTGAAGGAAGCATACGATACCCCGCATGGAATGGGATAATATCACAGGAGGTACTAGACTACCTTTCATCCTACATAAATAGACGCATATAAGTACGCATTTAAGCATAAACACGCACTATGCCGTTCTTCTCATGTATATATATATACAGGCAACACGCAGATATAGGTGCGACGTGAACAGTGAGCTGTATGTGCGCAGCTCGCGTTGCATTTTCGGAAGCGCTCGTTTTCGGAAACGCTTTGAAGTTCCTATTCCGAAGTTCCTATTCTCTAGAAAGTATAGGAACTTCAGAGCGCTTTTGAAAACCAAAAGCGCTCTGAAGACGCACTTTCAAAAAACCAAAAACGCACCGGACTGTAACGAGCTACTAAAATATTGCGAATACCGCTTCCACAAACATTGCTCAAAAGTATCTCTTTGCTATATATCTCTGTGCTATATCCCTATATAACCTACCCATCCACCTTTCGCTCCTTGAACTTGCATCTAAACTCGACCTCTACATTTTTTATGTTTATCTCTAGTATTACTCTTTAGACAAAAAAATTGTAGTAAGAACTATTCATAGAGTGAATCGAAAACAATACGAAAATGTAAACATTTCCTATACGTAGTATATAGAGACAAAATAGAAGAAACCGTTCATAATTTTCTGACCAATGAAGAATCATCAACGCTATCACTTTCTGTTCACAAAGTATGCGCAATCCACATCGGTATAGAATATAATCGGGGATGCCTTTATCTTGAAAAAATGCACCCGCAGCTTCGCTAGTAATCAGTAAACGCGGGAAGTGGAGTCAGGCTTTTTTTATGGAAGAGAAAATAGACACCAAAGTAGCCTTCTTCTAACCTTAACGGACCTACAGTGCAAAAAGTTATCAAGAGACTGCATTATAGAGCGCACAAAGGAGAAAAAAAGTAATCTAAGATGCTTTGTTAGAAAAATAGCGCTCTCGGGATGCATTTTTGTAGAACAAAAAAGAAGTATAGATTCTTTGTTGGTAAAATAGCGCTCTCGCGTTGCATTTCTGTTCTGTAAAAATGCAGCTCAGATTCTTTGTTTGAAAAATTAGCGCTCTCGCGTTGCATTTTTGTTTTACAAAAATGAAGCACAGATTCTTCGTTGGTAAAATAGCGCTTTCGCGTTGCATTTCTGTTCTGTAAAAATGCAGCTCAGATTCTTTGTTTGAAAAATTAGCGCTCTCGCGTTGCATTTTTGTTCTACAAAATGAAGCACAGATGCTTCGTT",
    copyNumber: 20,
    source: "features.json[125]: 2μ ori (1343 bp)",
  },
  {
    id: "cen_ars",
    name: "CEN/ARS (low-copy yeast)",
    type: "ori",
    organisms: ["yeast"],
    description:
      "Yeast centromere + autonomously replicating sequence (CEN/ARS). Low-copy origin: 1-2 copies per cell — behaves like a yeast chromosome. Used in pRS centromeric vectors for stable, low-level expression without selection pressure. Much more stable than 2μ vectors. Use when protein is toxic at high levels or when consistent expression is more important than yield.",
    seq: "GATCGCTTGCCTGTAACTTACACGCGCCTCGTATCTTTTAATGATGGAATAATTTGGGAATTTACTCTGTGTTTATTTATTTTTATGTTTTGTATTTGGATTTTAGAAAGTAAATAAAGAAGGTAGAAGAGTTACGGAATGAAGAAAAAAAAATAAACAAAGGTTTAAAAAATTTCAACAAAAAGCGTACTTTACATATATATTTATTAGACAAGAAAAGCAGATTAAATAGATATACATTCGATTAACGATAAGTAAAATGTAAAATCACAGGATTTTCGTGTGTGGTCTTCTACACAGACAAGATGAAACAATTCGGCATTAATACCTGAGAGCAGGAAGAGCAAGATAAAAGGTAGTATTTGTTGGCGATCCCCCTAGAGTCTTTTACATCTTCGGAAAACAAAAACTATTTTTTCTTTAATTTCTTTTTTTACTTTCTATTTTTAATTTATATATTTATATTAAAAAATTTAAATTATAATTATTTTTATAGCACGTGAT",
    copyNumber: 1,
    source: "features.json[280]: CEN/ARS (504 bp)",
  },

  // ── Yeast selection markers ───────────────────────────────────────────────

  {
    id: "leu2_marker",
    name: "LEU2 marker",
    type: "marker",
    organisms: ["yeast"],
    description:
      "S. cerevisiae LEU2 (β-isopropylmalate dehydrogenase) selectable marker: LEU2 promoter + LEU2 CDS. Complements leu2 auxotrophy — use in leu2Δ strains (BY4741, W303-1A, most lab strains). Select on synthetic complete media lacking leucine (SC-Leu). No antibiotic required. Most common yeast selection marker in pRS415, pYES series vectors.",
    seq: "AACTGTGGGAATACTCAGGTATCGTAAGATGCAAGAGTTCGAATCTCTTAGCAACCATTATTTTTTTCCTCAACATAACGAGAACACACAGGGGCGCTATCGCACAGAATCAAATTCGATGACTGGAAATTTTTTGTTAATTTCAGAGGTCGCCTGACGCATATACCTTTTTCAACTGAAAAATTGGGAGAAAAAGGAAAGGTGAGAGGCCGGAACCGGCTTTTCATATAGAATAGAGAAGCGTTCATGACTAAATGCTTGCATCACAATACTTGAAGTTGACAATATTATTTAAGGACCTATTGTTTTTTCCAATAGGTGGTTAGCAATCGTCTTACTTTCTAACTTTTCTTACCTTTTACATTTCAGCAATATATATATATATTTCAAGGATATACCATTCTAATGTTTGTTCCTAAGAAGATCGTCGTTTTGCCAGGTGACCACGTTGGTCAAGAAATCACAGCCGAAGCCATTAAGGTTCTTAAAGCTATTTCTGATGTTCGTTCCAATGTCAAGTTCGATTTCGAAAATCATTTAATTGGTGGTGCTGCTATCGATGCTACAGGTGTCCCACTTCCAGATGAGGCACTGGAAGCCTCCAAGAAGGTTGATGCCGTTTTGTTAGGTGCTGTGGGTGGTCCAAAATGGGGTACCGGTAGTGTTAGACCTGAACAAGGTTTACTAAAAATCCGTAAAGAACTTCAATTGTACGCCAACTTAAGACCATGTAACTTTGCATCCGACTCTCTTTTAGACTTATCTCCAATCAAGCCACAATTTGCTAAAGGTACTGACTTCGTTGTTGTCAGAGAATTAGTGGGAGGTATTTACTTTGGTAAGAGAAAGGAAGACGATGGTGATGGTGTCGCTTGGGATAGTGAACAATACACCGTTCCAGAAGTGCAAAGAATCACAAGAATGGCCGCTTTCATGGCCCTACAACATGAGCCACCATTGCCTATTTGGACCTTGGATAAAGCTAATGTTTTGGCCTCTTCAAGATTATGGAGAAAAACTGTGGAGGAAACCATCAAGAACGAATTCCCTACATTGAAGGTTCAACATCAATTGATTGATTCTGCCGCCATGATCCTAGTTAAGAACCCAACCCACCTAAATGGTATTATAATCACCAGCAACATGTTTGGTGATATCATCTCCGATGAAGCCTTACGTTATCCAGGTTCCTTGGGTTTGTTGCCATCTGCGTCCTTGGCCTCTTTGCCAGACAAGAACACCGCATTTGGTTTGTACGAACCATGCCACGGTTCTGCTCCCGGATTTGCCAAGAATAAGGTTGACCCTATCGCCACTATCTTGTCTGCTGCAATGATGTTGAAATTGTCATTGAACTTGCCTGAAGAAGGTAAGGCCATTGAAGATGCAGTTAAAAAGGTTTTGGATGCAGGTATCAGAACTGGTGATTTAGGTGGTTCCAACAGTACCACCGAAGTCGGTGATGCTGTCGCCGAAGAAGTTAAGAAAATCCTTGCTTAA",
    source: "features.json: LEU2 promoter (405 bp) + LEU2 CDS (1095 bp) = 1500 bp",
  },
  {
    id: "trp1_marker",
    name: "TRP1 marker",
    type: "marker",
    organisms: ["yeast"],
    description:
      "S. cerevisiae TRP1 (anthranilate synthase) selectable marker: TRP1 promoter + TRP1 CDS. Complements trp1 auxotrophy — use in trp1Δ strains (BY4742, W303-1B). Select on synthetic complete media lacking tryptophan (SC-Trp). Used in pRS424, pGAL4 series vectors. Alternative to LEU2 for dual-marker two-plasmid experiments.",
    seq: "AATTCGGTCGAAAAAAGAAAAGGAGAGGGCCAAGAGGGAGGGCATTGGTGACTATTGAGCACGTGAGTATACGTGATTAAGCACACAAAGGCAGCTTGGAGTATGTCTGTTATTAATTTCACAGGTAGTTCTGGTCCATTGGTGAAAGTTTGCGGCTTGCAGAGCACAGAGGCCGCAGAATGTGCACTAGATTCCGATGCTGACTTGCTGGGTATTATATGTGTGCCCAATAGAAAGAGAACAATTGACCCGGTTATTGCAAGGAAAATTTCAAGTCTTGTAAAAGCATATAAAAATAGTTCAGGCACTCCGAAATACTTGGTTGGCGTGTTTCGTAATCAACCTAAGGAGGATGTTTTGGCTCTGGTCAATGATTACGGCATTGATATCGTCCAACTGCATGGAGATGAGTCGTGGCAAGAATACCAAGAGTTCCTCGGTTTGCCAGTTATTAAAAGACTCGTATTTCCAAAAGACTGCAACATACTACTCAGTGCAGCTTCACAGAAACCTCATTCGTTTATTCCCTTGTTTGATTCAGAAGCAGGTGGGACAGGTGAACTTTTGGATTGGAACTCGATTTCTGACTGGGTTGGAAGGCAAGAGAGCCCCGAGAGCTTACATTTTATGTTAGCTGGTGGACTGACGCCAGAAAATGTTGGTGATGCGCTTAGATTAAATGGCGTTATTGGTGTTGATGTAAGCGGAGGTGTGGAGACAAATGGTGTAAAAGACTCTAACAAAATAGCAAATTTCGTCAAAAATGCTAAGAAATAG",
    source: "features.json: TRP1 promoter (102 bp) + TRP1 CDS (675 bp) = 777 bp",
  },
];

// ── Lookup by ID ──────────────────────────────────────────────────────────────

export const PARTS_BY_ID: Record<string, Part> = Object.fromEntries(
  PARTS_CATALOG.map((p) => [p.id, p]),
);

/** Format the catalog as a readable prompt context for Claude, grouped by organism. */
export function formatCatalogForPrompt(): string {
  const lines: string[] = ["== AVAILABLE PARTS =="];

  const orgGroups: { label: string; org: Organism; types: PartType[] }[] = [
    {
      label: "E. COLI PARTS",
      org: "ecoli",
      types: ["promoter", "rbs", "terminator", "ori", "marker"],
    },
    {
      label: "MAMMALIAN CELL PARTS",
      org: "mammalian",
      types: ["promoter", "rbs", "terminator", "ori", "marker"],
    },
    {
      label: "YEAST (S. cerevisiae) PARTS",
      org: "yeast",
      types: ["promoter", "terminator", "ori", "marker"],
    },
    {
      label: "CDS LIBRARY (all organisms — reporters, purification tags, genome editors)",
      org: "universal",
      types: ["cds"],
    },
  ];

  const typeHeaders: Partial<Record<PartType, string>> = {
    promoter: "Promoters",
    rbs: "RBS / Translation initiation",
    terminator: "Terminators / PolyA signals",
    ori: "Origins of replication",
    marker: "Selection markers",
    cds: "CDS",
  };

  for (const { label, org, types } of orgGroups) {
    const partsInGroup = PARTS_CATALOG.filter(
      (p) => p.organisms.includes(org) && types.includes(p.type),
    );
    if (partsInGroup.length === 0) continue;

    lines.push(`\n=== ${label} ===`);
    for (const type of types) {
      const partsOfType = partsInGroup.filter((p) => p.type === type);
      if (partsOfType.length === 0) continue;
      lines.push(`\n${typeHeaders[type] ?? type.toUpperCase()}:`);
      for (const p of partsOfType) {
        lines.push(`  • ${p.name} (id: "${p.id}", ${p.seq.length} bp)`);
        lines.push(`    ${p.description}`);
      }
    }
  }

  return lines.join("\n");
}
